# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  db-data:
