image: node:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - mkdir -p /app && export WORK_DIR=$(pwd) && cd /app && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip > /dev/null && ./aws/install && cd $WORK_DIR
    - apt-get update -y
    - apt-get install -y groff
    - aws --version
    - apt-get install -y jq
    - jq --version
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install -g aws-sdk
  script:
    - ./scripts/deploy.sh
  environment: prod
